version: "3.8"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql-store:/var/lib/mysql
      - ./entrypoint.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--password=mysql"]
      timeout: 10s
      interval: 30s
      retries: 3
      start_period: 60s

  redis:
    image: redis:4.0-alpine
    volumes:
      - redis-store:/data
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  mysql-store:
  redis-store:
